server:
  port: 8087
  context-path: /Solr

# zookeeper参数
zk:
   host: cdh-slaver2:2181,cdh-slaver3:2181,cdh-slaver4:2181/solr
   connect:
      timeout: 6000
   client:
      timeout: 15000

# collections
solr:
   collection:
      ip: IP